version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgresql
    network_mode: "host"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  cestx_net:
    driver: host
