version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgresql
    networks:
      cestx_net:
        ipv4_address: 192.168.4.61
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  cestx_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.4.0/22
