---
- name: Install Ansible
  hosts: "{{ service }}"
  remote_user: root
  become: yes

  tasks:
    - name: Determine package manager
      package_facts:
        manager: auto

    - name: Install Python and pip (if needed)
      block:
        - name: Install Python (Debian/Ubuntu)
          apt:
            name:
              - python3
              - python3-pip
            state: present
          when: ansible_facts.os_family == 'Debian'

        - name: Install Python (Red Hat/CentOS/Fedora)
          yum:
            name:
              - python3
              - python3-pip
            state: present
          when: ansible_facts.os_family == 'RedHat'

    - name: Install Ansible
      package:
        name: ansible
        state: present
