---
- name: Check Service and Repository Existence
  hosts: "{{ service }}"
  remote_user: root
  become: yes

  tasks:
    - name: Check if repository is cloned
      stat:
        path: "/home/cestx/.git"
      register: repo_status

    - name: Check if service is running
      ansible.builtin.systemd:
        name: "{{ service }}.service"
      register: status
      ignore_errors: true

    - name: Report Results
      debug:
        msg: "{{ repo_status.stat.exists and status.status.ActiveState == 'active'}}"

    - name: Print output to file
      ansible.builtin.copy:
        content: "{{ repo_status.stat.exists and status.status.ActiveState == 'active'}}"
        dest: /tmp/check_result.txt
      delegate_to: localhost
