---
- name: Check Service and Repository Existence
  hosts: "{{ service }}"
  remote_user: root
  become: yes

  tasks:
    - name: Check if repository is cloned
      stat:
        path: "/home/cestx/.git"
      register: repo_status

    - name: Check if service is running
      ansible.builtin.systemd_service:
        name: "{{ service }}.service"
      register: status
      ignore_errors: true

    - name: Report Results
      debug:
        msg: |
          Repository exists: {{ repo_status.stat.exists }}
          Service is active: {{ status.status.ActiveState == 'active'}}

    # - name: Print output to file
    #   ansible.builtin.copy:
    #     content: "Repository exists: {{ repo_status.stat.exists }}, Service is active: {{ status.status.ActiveState == 'active'}}"
    #     dest: /tmp/latest_commit.txt
    #     force: yes
    #     mode: "0666"
    #   delegate_to: localhost
