---
- name: Install Go on Ubuntu
  hosts: all
  remote_user: root
  become: yes

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Go
      apt:
        name: golang
        state: present
