services:
  hosts:
    registry:
      ansible_host: 192.168.4.63
      ansible_ssh_private_key_file: ~/.ssh/master
    logging-s:
      ansible_host: 192.168.4.64
      ansible_ssh_private_key_file: ~/.ssh/master
    task-s:
      ansible_host: 192.168.4.65
      ansible_ssh_private_key_file: ~/.ssh/master
    dynoxy-s:
      ansible_host: 192.168.4.66
      ansible_ssh_private_key_file: ~/.ssh/master
    template-s:
      ansible_host: 192.168.4.67
      ansible_ssh_private_key_file: ~/.ssh/master
    machine-s:
      ansible_host: 192.168.4.68
      ansible_ssh_private_key_file: ~/.ssh/master
    api-gw:
      ansible_host: 192.168.4.69
      ansible_ssh_private_key_file: ~/.ssh/master

systems:
  hosts:
    redis:
      ansible_host: 192.168.4.60
      ansible_ssh_private_key_file: ~/.ssh/master
    postgresql:
      ansible_host: 192.168.4.61
      ansible_ssh_private_key_file: ~/.ssh/master
    rabbitmq:
      ansible_host: 192.168.4.62
      ansible_ssh_private_key_file: ~/.ssh/master
