---
- name: Setup Environment for systems
  hosts: "{{ target }}"
  remote_user: root
  become: yes
  vars:
    deploy_commands:
      redis: "docker compose up -d --force-recreate"
      postgresql: "docker compose up -d --force-recreate"
      rabbitmq: "docker compose up -d --force-recreate"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - golang
          - git
          - wget
          - curl
          - vim
          - nano
        state: present

    - name: Clone repository if not present
      git:
        repo: "https://github.com/nesiler/cestx"
        dest: "/home/cestx"

    - name: Run deploy command
      shell: "{{ deploy_commands[target] }}"
      args:
        chdir: "/home/cestx/{{ target }}"
