---
- name: Setup Environment and Deploy Service
  hosts: "{{ service }}"
  remote_user: root
  become: yes
  vars:
    deploy_command:
      registry: "go build -o {{ service }} && ./{{ service }}"
      logger-s: "go build -o {{ service }} && ./{{ service }}"
      taskmaster-s: "go build -o {{ service }} && ./{{ service }}"
      dynoxy-s: "go build -o {{ service }} && ./{{ service }}"
      template-s: "go build -o {{ service }} && ./{{ service }}"
      machine-s: "go build -o {{ service }} && ./{{ service }}"
      api-gw: "dotnet run"

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - golang
          - git
          - wget
          - curl
          - vim
          - nano
        state: present

    - name: Clone repository if not present
      ansible.builtin.git:
        repo: "https://github.com/nesiler/cestx"
        dest: "/home/cestx"

    - name: Pull latest changes
      git:
        repo: "https://github.com/nesiler/CESTX"
        dest: "/home/cestx"
        update: yes

    - name: Copy .env file to hosts
      ansible.builtin.copy:
        src: "/home/cestx/.env"
        dest: "/home/cestx/.env"

    - name: Source environment variables from .env file
      ansible.builtin.shell: |
        set -a
        source /home/cestx/.env
        set +a
      args:
        executable: /bin/bash

    - name: Copy service file
      ansible.builtin.template:
        src: "services/{{ service }}.service"
        dest: "/etc/systemd/system/{{ service }}.service"

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start service
      ansible.builtin.systemd:
        name: "{{ service }}"
        enabled: yes
        state: started

    - name: Deploy Service
      ansible.builtin.shell: |
        cd /home/cestx/{{ service }}
        {{ deploy_command[service] }}
