---
- name: Update Service and Restart
  hosts: "{{ service }}"
  remote_user: root
  become: yes

  tasks:
    - name: Pull latest changes
      git:
        repo: "https://github.com/nesiler/cestx"
        dest: "/home/cestx"
        update: yes
        force: yes

    - name: Build Go executable
      ansible.builtin.shell: /usr/bin/go build -o {{ service }}
      args:
        chdir: /home/cestx/{{ service }}

    - name: Restart the service
      systemd:
        name: "{{ service }}"
        state: restarted
