version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    network_mode: "host"
    volumes:
      - ./minio_data:/data
    ports:
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data

networks:
  cestx_net:
    driver: host
