version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    network_mode: "host"
    volumes:
      - ./redis_data:/data
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=192.168.4.60
      - REDIS_PORT=6379

networks:
  cestx_net:
    driver: host
