version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    networks:
      proxmox_net:
        ipv4_address: 192.168.4.60
    volumes:
      - ./redis_data:/data
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=192.168.4.60
      - REDIS_PORT=6379

networks:
  proxmox_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.4.0/22
